sudo: required
dist: trusty
language: node_js
node_js:
  - '4.6'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g npm@4.0
  - npm install -g angular-cli
  - npm install @angular/tsc-wrapped autoprefixer loader-utils #fix travis-ci missing package 
  - npm install

script: 
  - npm run lint
  - npm run test

deploy:
  skip_cleanup: true
  provider: script
  script: ng github-pages:deploy --message "Deploy to GitHub Pages"
  
